tools:
    shell:
        allow:
            - cd *
            - git log *
            - ls *
            - echo *
            - go version
            - which go
            - find *
            - head *
